import js from "@eslint/js";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import prettier from "eslint-config-prettier";
import globals from "globals";
import tseslint from "typescript-eslint";

/**
 * The previous frontend had no linter at all, which is how a `mountedRef`
 * cleanup bug survived into a shipped build. `react-hooks` is the rule set that
 * matters most here: it is what catches effects that are not StrictMode-safe
 * and dependency arrays that lie.
 */
export default tseslint.config(
  {
    ignores: [
      "dist/**",
      "output/**",
      "node_modules/**",
      ".playwright-cli/**",
      "coverage/**",
      "src/api/legacy-client.ts", // superseded, kept unimported for reference
      "src/api/schema.ts", // generated by `npm run gen:api`; not hand-editable
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  reactHooks.configs.flat["recommended-latest"],
  {
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2022,
      globals: { ...globals.browser },
    },
    plugins: { "react-refresh": reactRefresh },
    rules: {
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      // `Foo | (string & {})` keeps autocomplete for known values while
      // tolerating enum values a newer backend may send.
      "@typescript-eslint/no-empty-object-type": "off",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "no-console": ["warn", { allow: ["warn", "error"] }],
      eqeqeq: ["error", "always", { null: "ignore" }],
    },
  },
  {
    files: ["**/*.test.{ts,tsx}", "src/test/**/*.{ts,tsx}"],
    languageOptions: { globals: { ...globals.browser, ...globals.node } },
  },
  {
    files: ["*.config.{js,ts}"],
    languageOptions: { globals: { ...globals.node } },
  },
  {
    // Build tooling: `npm run gen:api`. Node, not a browser, and it reports by printing.
    files: ["scripts/**/*.mjs"],
    languageOptions: { globals: { ...globals.node } },
    rules: { "no-console": "off" },
  },
  prettier,
);
