/**
 * The API contract, as the app sees it.
 *
 * Everything below either comes from `./schema` — generated by `npm run gen:api` from the
 * backend's own OpenAPI document — or is a client-side shape the API has no opinion about.
 * There is deliberately no third category: a type describing a response that is written by
 * hand here is a type free to disagree with the server, which is what this file replaced.
 *
 * The aliases exist because the wire names and the names that read well in a component are
 * not always the same (`Event` is an event of a run; `RunConfigIn` is just the config).
 * They are aliases, not copies — rename a field in pydantic and the compiler finds every
 * use of it here.
 */

export type {
  BudgetByRole,
  CompareAnalytics,
  CompareDelta,
  CompareGraft,
  CompareMovement,
  ContextDocRef,
  ControlAction,
  DirectionHint,
  EventTicket,
  FeedbackEntry,
  GraftEvent,
  GraphEdge,
  GraphMeta,
  GraphNode,
  GroundingDepth,
  HaltAllResponse,
  Harness,
  HypothesisDetail,
  HypothesisRow,
  HypothesisSource,
  HypothesisStatus,
  IdentityResponse,
  Lifecycle,
  MatchRow,
  MatchSide,
  MatchStatus,
  ModelChoiceBrief,
  ModelSettingsUpdate,
  ModelTier,
  ModelsBrief,
  Provider,
  ProviderBrief,
  ReviewRow,
  RoleModelBrief,
  RoundSummary,
  RunBudget,
  RunCounts,
  RunDetail,
  RunGraph,
  RunSource,
  RunSummary,
  RunnerKind,
  Workshop,
  WorkshopError,
  WorkshopOption,
  WorkshopState,
} from "./schema";

export {
  CONTROL_ACTION_VALUES as CONTROL_ACTIONS,
  GROUNDING_DEPTH_VALUES as GROUNDING_DEPTHS,
  HARNESS_VALUES as HARNESSES,
  HYPOTHESIS_STATUS_VALUES as HYPOTHESIS_STATUSES,
  LIFECYCLE_VALUES as LIFECYCLES,
  MATCH_STATUS_VALUES as MATCH_STATUSES,
  MODEL_TIER_VALUES as MODEL_TIERS,
  PROVIDER_VALUES as PROVIDERS,
  RUNNER_KIND_VALUES as RUNNERS,
  RUN_SOURCE_VALUES as RUN_SOURCES,
  WORKSHOP_STATE_VALUES as WORKSHOP_STATES,
} from "./schema";

import type {
  CapabilitiesResponse,
  ContextDocIn,
  CreateRunRequest,
  Event,
  GraftConfigIn,
  Harness,
  HarnessHealthStatus,
  HealthResponse,
  IdentityResponse,
  ModelChoiceBrief,
  ModelOverrideIn,
  ModelSettingsResponse,
  ModelTier,
  ModelTableEntry,
  ModelsBrief,
  RoleModelBrief,
  RunConfigIn,
  RunControlRequest,
  RunControlResponse,
  RunList,
  RunTop,
  WorkshopRecommendedSettings,
} from "./schema";

/* --- Aliases: the same shapes under the names the app reads best ----------- */

/** One row of `run_events`. `Event` alone is ambiguous next to the DOM's. */
export type RunEvent = Event;

/**
 * A run's settings, all of them.
 *
 * `RunConfigIn` is the request body, where every field may be left out for the backend to
 * default. The wizard is on the other side of that: it decides every value before it
 * offers a Launch button, and the Confirm step estimates cost from the lot. `Required`
 * says so, and keeps the estimator from having to defend against a missing `rounds`.
 */
export type GraftConfig = Required<GraftConfigIn>;

/**
 * Three fields are narrowed past `Required` as well as made mandatory, because
 * on the wire their `null` means "let the backend choose" and the wizard is the
 * thing doing the choosing: it resolves a tier and a table before it will show a
 * Launch button. `provider` keeps its `null`, because "whatever the stored
 * default resolves to" is a real answer for a run nobody has set a vendor on.
 */
export type RunConfig = Omit<
  Required<RunConfigIn>,
  "graft" | "model_tier" | "model_overrides"
> & {
  graft: GraftConfig;
  model_tier: ModelTier;
  model_overrides: Record<string, ModelOverrideIn>;
};
export type ContextDocInput = ContextDocIn;
export type ModelTableRow = ModelTableEntry;
export type TopHypothesis = RunTop;
export type RecommendedSettings = WorkshopRecommendedSettings;
export type CreateRunInput = CreateRunRequest;

/**
 * The harnesses a run can actually be launched against.
 *
 * Narrower than `Harness`: codex is something `/health` probes for and nothing more —
 * `POST /runs` refuses it. Derived from the request body so it cannot drift from what the
 * server accepts.
 */
export type LaunchHarness = NonNullable<CreateRunRequest["harness"]>;
export type ControlResponse = RunControlResponse;

/**
 * The three fields `continue` carries: how many more rounds, optionally a raised call
 * ceiling, and optionally a raised or removed cost ceiling. Derived from the generated
 * request body rather than written out, so a field renamed on the backend is a compile
 * error here instead of a silent 422.
 *
 * `budget_usd` is the one field whose absence and whose `null` mean different things —
 * leave the ceiling alone, versus take it off — so it must be omitted from the body
 * rather than sent as `undefined` when there is nothing to say about it.
 */
export type ControlExtension = Pick<
  RunControlRequest,
  "add_rounds" | "budget_calls" | "budget_usd"
>;
export type RunListPage = RunList;
export type Health = HealthResponse;
export type HarnessProbe = HarnessHealthStatus;
export type Capabilities = CapabilitiesResponse;
export type CurrentIdentity = IdentityResponse;

/* --- The provider/model surface -------------------------------------------
   Aliases only. Every shape below is generated from the backend's OpenAPI; the
   names exist because the wire name and the name that reads well in a component
   are not always the same, and because four surfaces spell "the models block of
   the capabilities payload" and none of them should spell it twice.
   -------------------------------------------------------------------------- */

/** The `models` block of `GET /api/capabilities` — the whole role table. */
export type ModelsPayload = ModelsBrief;
/** One model a step may be set to, with its own effort ladder and reach. */
export type ModelChoice = ModelChoiceBrief;
/** One resolved step: what it runs on, how hard it thinks, and why. */
export type RoleModelRow = RoleModelBrief;
/** The persisted system default, as `GET /api/settings/models` serves it. */
export type ModelSettings = ModelSettingsResponse;
/** One step's `{ model?, effort? }`, as both the launch body and settings type it. */
export type ModelSettingsChoice = ModelOverrideIn;

/* --- Vocabularies the API does not guarantee -------------------------------
   These are open sets on the wire: `run_events.type` has no CHECK constraint, and a
   verdict, novelty level and operator are written by the model. The lists below are what
   the app knows how to render — everything else falls through to a neutral presentation
   rather than being dropped, so a new event type from a newer engine still shows up.
   -------------------------------------------------------------------------- */

/** Plan C3's `run_events.type` enum: the types with a dedicated presentation. */
export const EVENT_TYPES = [
  "round_started",
  "hypothesis_added",
  "review_recorded",
  "cluster_applied",
  "graft_fired",
  "graft_abstained",
  "match_completed",
  "feedback_recorded",
  "round_completed",
  "call_started",
  "call_finished",
  "rate_limited",
  "role_degraded",
  "contract_violation",
  "step_failed",
  "schema_repaired",
  "context_truncated",
  "report_skipped",
  "note_added",
  "hypothesis_archived",
  "budget_warning",
  "lifecycle_changed",
  "run_extended",
  "run_finished",
  "run_failed",
] as const;
export type EventType = (typeof EVENT_TYPES)[number];

export const VERDICTS = ["pass", "reject"] as const;
export type Verdict = (typeof VERDICTS)[number];

export const NOVELTY_LEVELS = ["high", "moderate", "low"] as const;
export type NoveltyLevel = (typeof NOVELTY_LEVELS)[number];

export const OPERATORS = [
  "grounding",
  "combination",
  "simplification",
  "out_of_box",
] as const;
export type Operator = (typeof OPERATORS)[number];

export const ROLES = [
  "framing",
  "verification",
  "synthesis",
  "challenge",
  "generation",
  "reflection",
  "proximity",
  "ranking",
  "evolution",
  "meta_review",
  "cartographer",
  "overview",
  "workshop",
] as const;
export type Role = (typeof ROLES)[number];

export const EFFORTS = ["low", "medium", "high", "xhigh", "max"] as const;
export type Effort = (typeof EFFORTS)[number];

/* --- Client-side shapes ----------------------------------------------------
   Query strings and error envelopes: things the app sends or reads that are not a
   component of the OpenAPI document.
   -------------------------------------------------------------------------- */

/** The `{code, message, details?}` body every failing endpoint returns. */
export type ErrorEnvelope = {
  code: string;
  message: string;
  details?: unknown;
};

/** `GET /runs?sort=` — an enum on the backend, so it is one here too. */
export const RUN_SORTS = ["recent", "oldest", "title", "calls"] as const;
export type RunSort = (typeof RUN_SORTS)[number];

/** `GET /runs/{id}/hypotheses?sort=`. */
export const HYPOTHESIS_SORTS = ["elo", "hid", "recent"] as const;
export type HypothesisSort = (typeof HYPOTHESIS_SORTS)[number];

export type RunsQuery = {
  /** Server-side lifecycle/bucket filter. Values are the backend's; pass through. */
  status?: string;
  harness?: Harness;
  q?: string;
  show_archived?: boolean;
  /** Demo runs are practice and stay out of the list unless asked for. */
  include_demo?: boolean;
  /** `true` is the current workspace; administrators deliberately pass `false` for all. */
  mine?: boolean;
  sort?: RunSort | (string & {});
  page?: number;
  page_size?: number;
};
