/**
 * The idea graph, advanced one SSE event at a time.
 *
 * `GET /api/runs/{id}/graph` answers what the graph looks like now; this module answers
 * what it looks like a moment later, without asking again. That matters because the graph
 * is the Ideas tab's main surface during a live run: refetching on every event would
 * reshuffle an organic layout under the reader's cursor several times a round.
 *
 * Three rules hold throughout:
 *
 * * **Pure.** No DOM, no clock, no randomness. Same model plus same event, same result.
 * * **New model or same reference.** Something changed, the caller gets a new object; nothing
 *   changed, it gets the object it passed in. The store compares by reference, so returning
 *   a fresh-but-identical model would re-render — and re-lay-out — the whole graph for free.
 * * **Never throws.** `run_events.type` is an open set with no CHECK constraint behind it. An
 *   event type a newer engine invents must fall through untouched, not blow up the tab.
 *
 * Every payload read here is checked against `backend/app/engine/events.py`, which is the
 * contract for what each type actually carries. Two of the design's five live events carry
 * nothing per-node — see `needsRefetchFor`.
 */

import type {
  GraphEdge,
  GraphMeta,
  GraphNode as ApiGraphNode,
  RunGraph as ApiRunGraph,
  RunEvent,
} from "../../api/types";
import { shortLabel } from "./shortLabel";

/**
 * The `RunGraph` DTO the graph endpoint returns, generated by `npm run gen:api` from the
 * backend's own OpenAPI document and re-exported here rather than copied.
 *
 * These were hand-written while the endpoint was still in flight. Re-exporting instead
 * means a field renamed in pydantic is a compile error in this file rather than a live
 * model that quietly disagrees with the shape a refetch returns.
 */
export type { GraphEdge, GraphMeta } from "../../api/types";

/**
 * The endpoint's node, plus the phrase the canvas draws under its circle.
 *
 * `label` is the one field on a node that the server has no opinion about, and it is
 * added here rather than in the view for a reason: it is derived from `title`, and a
 * derivation done in a render is a derivation done fifty-nine times a frame *and* a
 * second copy of the rule that the layout — which is spaced against the widest label a
 * run can produce — could quietly disagree with. Every node in the app gets its label in
 * exactly two places, both in this file: {@link withLabels} for a fetched graph and
 * `addHypothesis` for one that arrived on the stream.
 */
export interface GraphNode extends ApiGraphNode {
  label: string;
}

export interface RunGraph extends Omit<ApiRunGraph, "nodes"> {
  nodes: GraphNode[];
}

/**
 * A graph as the endpoint returned it, labelled for the canvas.
 *
 * Called once where the response lands, so that everything downstream — the layouts, the
 * component, the rail — sees one shape and never has to ask whether a node was fetched or
 * streamed.
 */
export function withLabels(graph: ApiRunGraph): RunGraph {
  return {
    ...graph,
    nodes: graph.nodes.map((node) => ({
      ...node,
      label: shortLabel(node.title, node.hid),
    })),
  };
}

/**
 * The rating a hypothesis is born with — `hypotheses.elo`'s server default.
 *
 * `hypothesis_added` carries no rating because the row has not been rated yet. Guessing
 * anything else here would put a brand-new idea at a size it never had.
 */
export const START_ELO = 1200;

/**
 * Events that change the graph but do not say how, so the view must refetch.
 *
 * `cluster_applied` carries `{round, n_clusters, labelled, duplicates}` — run-level counts,
 * with no map from hid to cluster label and no list of which ideas were merged away. It is
 * the event behind two of the design's visual encodings (hue by cluster, hollow-dashed
 * duplicates) and it identifies no node at all. `graft_fired` carries `{round, votes,
 * n_clusters, hhi, source_domain, seed_id}` — the seeded hypotheses arrive later as ordinary
 * `hypothesis_added` events tagged with the same `seed_id`, and `GraphNode` has nowhere to
 * record that anyway.
 *
 * Rather than invent fields the backend does not emit, `applyEvent` leaves the model alone
 * and the caller re-reads `/graph` — twice a round at most, and never mid-generation.
 */
const REFETCH_EVENTS = new Set(["cluster_applied", "graft_fired"]);

export function needsRefetchFor(event: RunEvent): boolean {
  return REFETCH_EVENTS.has(event.type);
}

/** Advance the graph by one event. Returns the same reference when nothing changed. */
export function applyEvent(model: RunGraph, event: RunEvent): RunGraph {
  switch (event.type) {
    case "hypothesis_added":
      return addHypothesis(model, event);
    case "review_recorded":
      return recordReview(model, event);
    case "match_completed":
      return completeMatch(model, event);
    case "hypothesis_archived":
      return archiveHypothesis(model, event);
    default:
      // Includes the two refetch events above, and every type a later engine adds.
      return model;
  }
}

/**
 * Derive the meta block from the nodes and edges, exactly as `build_graph` does.
 *
 * Recomputed on every change rather than patched, so the live model always equals what a
 * refetch would have returned. The alternative — nudging `elo_max` when a match moves it —
 * drifts the moment an event is missed, and node radius is scaled from these two numbers.
 *
 * `lineage_recorded` is the one field that cannot be derived from nodes and edges: it is a
 * fact about the engine that wrote the run, not about what the run produced. It is carried
 * through from the fetched graph rather than guessed, because guessing `false` would make
 * a live run claim its lineage was lost the moment the first idea arrived.
 */
export function graphMeta(
  nodes: GraphNode[],
  edges: GraphEdge[],
  lineageRecorded: boolean,
): GraphMeta {
  let rounds = 1;
  // An empty graph reports a zero-width Elo band, as `build_graph`'s `elos or [0.0]` does.
  let eloMin = 0;
  let eloMax = 0;
  let hasClusters = false;
  for (const [index, node] of nodes.entries()) {
    if (node.created_round > rounds) rounds = node.created_round;
    if (index === 0 || node.elo < eloMin) eloMin = node.elo;
    if (index === 0 || node.elo > eloMax) eloMax = node.elo;
    if (node.cluster) hasClusters = true;
  }
  return {
    rounds,
    has_lineage: edges.length > 0,
    lineage_recorded: lineageRecorded,
    has_clusters: hasClusters,
    elo_min: eloMin,
    elo_max: eloMax,
    node_count: nodes.length,
  };
}

/* --- the handlers ---------------------------------------------------------- */

/** `{hid, title, round, source, operator?, parent_ids?, seed_id?}` */
function addHypothesis(model: RunGraph, event: RunEvent): RunGraph {
  const hid = readText(event.payload.hid);
  if (!hid || model.nodes.some((node) => node.hid === hid)) return model;

  const operator = readText(event.payload.operator);
  const title = readText(event.payload.title) ?? hid;
  const node: GraphNode = {
    hid,
    id: "",
    title,
    label: shortLabel(title, hid),
    status: "active",
    elo: START_ELO,
    matches: 0,
    wins: 0,
    created_round: readNumber(event.payload.round) ?? event.round ?? 1,
    operator,
    cluster: null,
    duplicate_of: null,
    source: readText(event.payload.source) === "human" ? "human" : "agent",
    is_leader: false,
  };

  const nodes = insertByHid(model.nodes, node);
  // Only parents already in the graph, the same filter `build_graph` applies: an edge to a
  // hid nothing draws is an arrow from nowhere.
  const known = new Set(nodes.map((existing) => existing.hid));
  const parents = [...new Set(readTextList(event.payload.parent_ids))].filter(
    (parent) => parent !== hid && known.has(parent),
  );
  const edges = insertEdges(
    model.edges,
    hid,
    parents.map((parent) => ({ parent, child: hid, operator })),
  );

  return rebuild(model, withLeader(nodes), edges);
}

/** `{hid, verdict, novelty_level}` — a `reject` retires the hypothesis in the same commit. */
function recordReview(model: RunGraph, event: RunEvent): RunGraph {
  if (readText(event.payload.verdict) !== "reject") return model;
  const hid = readText(event.payload.hid);
  const index = indexOfHid(model.nodes, hid);
  // `record_review` only moves an *active* row to rejected; a second review of an idea
  // already merged away must not resurrect it as a rejection.
  if (index < 0 || model.nodes[index].status !== "active") return model;

  const nodes = replaceAt(model.nodes, index, {
    ...model.nodes[index],
    status: "rejected",
  });
  return rebuild(model, withLeader(nodes), model.edges);
}

/**
 * `{match_id, round, hid_a, hid_b, winner, k, elo_a_before, elo_a_after, elo_b_before,
 * elo_b_after}` — `winner` is 1 for side a, 2 for side b, as the matches table stores it.
 *
 * A match nobody could judge is recorded with no winner and emits no event, so both sides
 * here always played: `matches` moves for each of them, `wins` for one.
 */
function completeMatch(model: RunGraph, event: RunEvent): RunGraph {
  const winner = readNumber(event.payload.winner);
  let nodes = scoreSide(
    model.nodes,
    readText(event.payload.hid_a),
    readNumber(event.payload.elo_a_after),
    winner === 1,
  );
  nodes = scoreSide(
    nodes,
    readText(event.payload.hid_b),
    readNumber(event.payload.elo_b_after),
    winner === 2,
  );
  if (nodes === model.nodes) return model;
  return rebuild(model, withLeader(nodes), model.edges);
}

/**
 * `{hid}` — the scientist retiring an idea by hand.
 *
 * Not in the design's live table, but it is the one event that moves a row to `archived`
 * with a hid attached. Without it a live graph keeps drawing a retired idea as active, and
 * possibly as the leader, until the tab is reloaded — the model would be quietly wrong
 * about the database, which is worse than being silent.
 */
function archiveHypothesis(model: RunGraph, event: RunEvent): RunGraph {
  const index = indexOfHid(model.nodes, readText(event.payload.hid));
  if (index < 0 || model.nodes[index].status === "archived") return model;

  const nodes = replaceAt(model.nodes, index, {
    ...model.nodes[index],
    status: "archived",
  });
  return rebuild(model, withLeader(nodes), model.edges);
}

/* --- shared machinery ------------------------------------------------------ */

function scoreSide(
  nodes: GraphNode[],
  hid: string | null,
  elo: number | null,
  won: boolean,
): GraphNode[] {
  const index = indexOfHid(nodes, hid);
  if (index < 0) return nodes;
  const node = nodes[index];
  return replaceAt(nodes, index, {
    ...node,
    elo: elo ?? node.elo,
    matches: node.matches + 1,
    wins: node.wins + (won ? 1 : 0),
  });
}

/**
 * Re-flag the leader: the highest Elo among active nodes, ties to the lowest hid.
 *
 * Rejections and matches both move it, and an all-rejected run has no leader at all — the
 * run that rejected 18 of 18 must not crown one of its corpses. Nodes whose flag did not
 * change keep their identity so React can skip them.
 */
function withLeader(nodes: GraphNode[]): GraphNode[] {
  let leader: GraphNode | null = null;
  for (const node of nodes) {
    if (node.status !== "active") continue;
    if (
      leader === null ||
      node.elo > leader.elo ||
      (node.elo === leader.elo && node.hid < leader.hid)
    ) {
      leader = node;
    }
  }

  let changed = false;
  const next = nodes.map((node) => {
    const isLeader = leader !== null && node.hid === leader.hid;
    if (isLeader === node.is_leader) return node;
    changed = true;
    return { ...node, is_leader: isLeader };
  });
  return changed ? next : nodes;
}

function rebuild(model: RunGraph, nodes: GraphNode[], edges: GraphEdge[]): RunGraph {
  return {
    run_id: model.run_id,
    nodes,
    edges,
    meta: graphMeta(nodes, edges, model.meta.lineage_recorded),
  };
}

/**
 * Insert keeping the array sorted by hid.
 *
 * `build_graph` orders by hid, and both layouts are deterministic functions of input order.
 * Appending instead would put a live graph in a different order from the same graph after a
 * reload, and the reader would watch it rearrange itself for no reason.
 */
function insertByHid(nodes: GraphNode[], node: GraphNode): GraphNode[] {
  const at = nodes.findIndex((existing) => existing.hid > node.hid);
  if (at < 0) return [...nodes, node];
  return [...nodes.slice(0, at), node, ...nodes.slice(at)];
}

/** The same idea for edges: grouped by child in hid order, parents in the order emitted. */
function insertEdges(edges: GraphEdge[], child: string, added: GraphEdge[]): GraphEdge[] {
  if (added.length === 0) return edges;
  const at = edges.findIndex((edge) => edge.child > child);
  if (at < 0) return [...edges, ...added];
  return [...edges.slice(0, at), ...added, ...edges.slice(at)];
}

function indexOfHid(nodes: GraphNode[], hid: string | null): number {
  if (!hid) return -1;
  return nodes.findIndex((node) => node.hid === hid);
}

function replaceAt(nodes: GraphNode[], index: number, node: GraphNode): GraphNode[] {
  const next = nodes.slice();
  next[index] = node;
  return next;
}

/* --- payload readers -------------------------------------------------------
   Payloads arrive as `Record<string, unknown>` because that is what the wire guarantees.
   Reading them defensively is what keeps the promise never to throw: a missing or
   mistyped field costs the graph one update, not the tab.
   -------------------------------------------------------------------------- */

function readText(value: unknown): string | null {
  return typeof value === "string" && value.length > 0 ? value : null;
}

function readNumber(value: unknown): number | null {
  return typeof value === "number" && Number.isFinite(value) ? value : null;
}

function readTextList(value: unknown): string[] {
  if (!Array.isArray(value)) return [];
  return value.filter(
    (item): item is string => typeof item === "string" && item.length > 0,
  );
}
